"""initial migration

Revision ID: 5ec577fbb73c
Revises: 
Create Date: 2018-10-26 13:51:15.780212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec577fbb73c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.Column('_password', sa.String(length=255), nullable=False),
    sa.Column('section', sa.String(length=45), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('rec_num', sa.SmallInteger(), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('rec_num')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.Column('_password', sa.String(length=255), nullable=True),
    sa.Column('rec_num', sa.String(length=24), nullable=True),
    sa.Column('bound_wechat', sa.String(length=45), nullable=True),
    sa.Column('reister_time', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('isban', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('company_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('sid', sa.String(length=24), nullable=False),
    sa.Column('service_id', sa.String(length=45), nullable=False),
    sa.Column('remit_sum', sa.String(length=45), nullable=False),
    sa.Column('tax_rank', sa.String(length=45), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_type', sa.String(length=45), nullable=False),
    sa.Column('province', sa.String(length=24), nullable=False),
    sa.Column('city', sa.String(length=24), nullable=False),
    sa.Column('bankName', sa.String(length=128), nullable=False),
    sa.Column('subBankName', sa.String(length=128), nullable=False),
    sa.Column('bankNo', sa.String(length=45), nullable=False),
    sa.Column('legalPersonName', sa.String(length=24), nullable=False),
    sa.Column('linkName', sa.String(length=24), nullable=False),
    sa.Column('linkPhone', sa.String(length=24), nullable=False),
    sa.Column('licenseNo', sa.String(length=45), nullable=False),
    sa.Column('idCardNo', sa.String(length=45), nullable=False),
    sa.Column('realNameVerify', sa.SmallInteger(), nullable=True),
    sa.Column('cofoundTime', sa.String(length=128), nullable=True),
    sa.Column('productType', sa.String(length=45), nullable=True),
    sa.Column('retaxFirstYear', sa.String(length=128), nullable=True),
    sa.Column('nationalTaxRegister', sa.String(length=128), nullable=True),
    sa.Column('recentRetaxAmount', sa.String(length=45), nullable=True),
    sa.Column('supplyProvince', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licenseNo')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('fund', sa.String(length=45), nullable=False),
    sa.Column('privilegeId', sa.Integer(), nullable=True),
    sa.Column('maxAmount', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('fundUrl', sa.String(length=255), nullable=True),
    sa.Column('online', sa.SmallInteger(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('accessDetails', sa.String(length=255), nullable=True),
    sa.Column('creditAmount', sa.String(length=255), nullable=True),
    sa.Column('guaranteeMeasure', sa.String(length=255), nullable=True),
    sa.Column('LoanTime', sa.String(length=255), nullable=True),
    sa.Column('repayment', sa.String(length=255), nullable=True),
    sa.Column('serviceFee', sa.String(length=255), nullable=True),
    sa.Column('serviceFeeDetail', sa.String(length=255), nullable=True),
    sa.Column('productStyle', sa.String(length=255), nullable=True),
    sa.Column('productInfo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bank_user_id'], ['bank_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cancelling_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_info_id', sa.Integer(), nullable=False),
    sa.Column('canselling_time', sa.String(length=128), nullable=False),
    sa.Column('batch_num', sa.String(length=128), nullable=False),
    sa.Column('canselling_bank', sa.String(length=128), nullable=False),
    sa.Column('canseliing_id', sa.String(length=128), nullable=False),
    sa.Column('add_value_tax', sa.String(length=128), nullable=False),
    sa.Column('k_mark', sa.String(length=128), nullable=False),
    sa.Column('k_time', sa.String(length=128), nullable=False),
    sa.Column('t_mark', sa.String(length=128), nullable=False),
    sa.Column('t_time', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['company_info_id'], ['company_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('contrat_name', sa.String(length=128), nullable=False),
    sa.Column('contract_file_url', sa.String(length=128), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['bank_user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loanapply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=128), nullable=False),
    sa.Column('rec_num', sa.SmallInteger(), nullable=True),
    sa.Column('section', sa.String(length=45), nullable=False),
    sa.Column('company_name', sa.String(length=45), nullable=False),
    sa.Column('product_name', sa.String(length=45), nullable=False),
    sa.Column('applyTime', sa.DateTime(), nullable=True),
    sa.Column('isFinish', sa.SmallInteger(), nullable=True),
    sa.Column('retaxId', sa.String(length=45), nullable=True),
    sa.Column('retaxDate', sa.String(length=24), nullable=True),
    sa.Column('retaxPc', sa.String(length=24), nullable=True),
    sa.Column('retaxAmount', sa.Float(), nullable=True),
    sa.Column('applyAmount', sa.Float(), nullable=True),
    sa.Column('grantDate', sa.Date(), nullable=True),
    sa.Column('dateline', sa.Date(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('acceptTime', sa.DateTime(), nullable=True),
    sa.Column('reviewTime', sa.DateTime(), nullable=True),
    sa.Column('loanAmount', sa.Float(), nullable=True),
    sa.Column('loanRate', sa.Float(), nullable=True),
    sa.Column('loanTerm', sa.Date(), nullable=True),
    sa.Column('riskTime', sa.DateTime(), nullable=True),
    sa.Column('rejectReason', sa.String(length=255), nullable=True),
    sa.Column('reviewOpinion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_info_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=24), nullable=True),
    sa.Column('license_num', sa.String(length=64), nullable=True),
    sa.Column('abilityScore', sa.Integer(), nullable=True),
    sa.Column('riskScore', sa.Integer(), nullable=True),
    sa.Column('creditScore', sa.Integer(), nullable=True),
    sa.Column('repayAbilityScore', sa.Integer(), nullable=True),
    sa.Column('legalScore', sa.Integer(), nullable=True),
    sa.Column('repayWillingScore', sa.Integer(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['company_info_id'], ['company_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('subTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('apply_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=False),
    sa.Column('file_url', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apply_id'], ['loanapply.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_file')
    op.drop_table('subscribe')
    op.drop_table('score')
    op.drop_table('loanapply')
    op.drop_table('contract_template')
    op.drop_table('cancelling_stocks')
    op.drop_table('product')
    op.drop_table('company_info')
    op.drop_table('company')
    op.drop_table('bank_user')
    # ### end Alembic commands ###
